import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Calligraffitti } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const font = Calligraffitti({
  weight: '400',
  subsets: ['latin']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${font.className} antialiased bg-third`}
      >
        <Header />
        <div className="mt-[60px]" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
